export function architecture({ projectName, description, techStack, date }) {
  return `# ${projectName} — Architecture Overview

> **Last updated:** ${date} | **Graphify corpus:** run \`graphify ./\` to populate GRAPH_REPORT.md

## What This Is

${description}

## Tech Stack

${techStack}

## How the Repos Connect

<!-- Describe how your repos talk to each other. Examples: -->
<!-- - Frontend calls backend API at /api/* -->
<!-- - Backend reads/writes to the database -->
<!-- - Shared types between repos -->

(Fill this in as you build.)

## Key Data Structures

<!-- List the most important models/schemas/types in your project. -->
<!-- These are the ones where a change ripples through multiple files. -->

(Fill this in as you build.)

## Key Communities (from Graphify)

<!-- After running Graphify, paste your top communities here. Example: -->
<!-- | Community | Core Nodes | Role | -->
<!-- |-----------|------------|------| -->
<!-- | C0 | page, admin handlers | Admin panel | -->

(Run \`graphify ./\` from workspace root to generate GRAPH_REPORT.md, then summarize key communities here.)

## Known Gaps

<!-- Things that are stored but not used, missing features, tech debt. -->

(Fill this in as you discover them.)
`;
}

export function moc({ projectName, vaultName, repos, date }) {
  const repoList = repos.map(r => `| [[${r}]] | Active | |`).join('\n');
  return `# Map of Content — ${projectName}

> Entry point for all agents. Read this first every session.

## Active Repos

| Repo | Status | Notes |
|------|--------|-------|
${repoList || '| (add repos) | Active | |'}

## Vault Files

| File | Purpose |
|------|---------|
| [[ARCHITECTURE_OVERVIEW]] | How the system works, key communities from Graphify |
| [[API_CONTRACTS]] | Endpoint shapes — final authority |
| [[DECISIONS]] | Rejected approaches, non-obvious choices |
| [[GRAPH_REPORT]] | Structural analysis: nodes, edges, communities, god nodes |
| [[SESSION_LOG]] | Two-line handoff notes per session |

## Session Start Sequence

1. Read this file (MOC.md)
2. Read DECISIONS.md — what's been tried and why
3. For current work: check SESSION_LOG.md for last handoff
4. For architecture questions: ARCHITECTURE_OVERVIEW.md → GRAPH_REPORT.md

## Last Updated

${date}
`;
}

export function graphReport({ projectName, date }) {
  return `# Graph Report — ${projectName}

> Generated by Graphify. Run \`graphify ./\` from the workspace root to update.
> Last run: ${date}

## How to Generate

\`\`\`bash
python3 -m venv .venv-graphify
source .venv-graphify/bin/activate
pip install graphifyy
graphify ./ --output ./${projectName}-vault/GRAPH_REPORT.md
\`\`\`

Use \`--no-semantic\` for a fast, free AST-only run (no Claude tokens):
\`\`\`bash
graphify ./ --no-semantic --output ./${projectName}-vault/GRAPH_REPORT.md
\`\`\`

## Corpus Check

(Not yet generated — run Graphify to populate)

## Summary

(Nodes · edges · communities)

## God Nodes (by betweenness centrality)

| Rank | Node | BC | Degree | Community |
|------|------|----|--------|-----------|
| | | | | |

## Communities

| ID | Size | Representative Nodes | Role |
|----|------|---------------------|------|
| | | | |

## Knowledge Gaps

(Fill in after running Graphify)

## Suggested Questions

(Graphify will generate these based on graph structure)
`;
}

export function apiContracts({ date }) {
  return `# API Contracts

> **Last updated:** ${date}
> If code and docs disagree, update the code. This file is the final authority.

## Endpoints

<!-- Document your API endpoints here. Example: -->
<!--
### POST /api/users
Creates a new user.
Request: { "email": "string", "name": "string" }
Response: { "id": "string", "email": "string", "name": "string" }
Errors: 400 (validation), 409 (duplicate email)
-->

(Add endpoints as you build them.)
`;
}

export function decisions({ date, author }) {
  return `# Decisions Log

> Reverse-chronological log of non-obvious decisions, rejected approaches, and dead ends.
> When you reject an approach or make a choice that isn't self-evident from the code, add an entry.
> Format: ## YYYY-MM-DD — Title (by [name]) followed by two sentences.
> Agents read this before suggesting alternatives you've already ruled out.

---

## ${date} — Workspace setup (by ${author})

Set up AI-augmented workspace with Obsidian vault as shared brain, CLAUDE.md for session context, and .ai-rules per repo. Vault is the single source of truth — agents read it before writing code.
`;
}

export function sessionLog() {
  return `# Session Log

> Two-line handoff notes at the end of each session.
> Helps the next session pick up where the last one left off.
> Format: ## YYYY-MM-DD — Session summary (by [name])
> Line 1: What was done. Line 2: Where things left off / what's next.

(No sessions logged yet.)
`;
}
